name: serverchan-action-test

on: [push]

jobs:
  serverchan:
    name: Serverchan test
    runs-on: ubuntu-latest
    steps:
    - name: ServerChan push
      env: 
        SC_KEY: ${{ secrets.SERVERCHAN_KEY }}
      run: |
        curl -d "text=您的OpenWRT系统已经编译完成啦ヾ(≧▽≦*)o&desp=编译结果下载地址：[奶牛快传](https://c-t.work/s/) | [wetransfer](https://we.tl/)<br/>[Link To GitHub Actions](https://github.com/)<br/>sha256:<br/>```a69e0d878d8f47c514dc59d12853d4b1aea5ad2e4c44753e5a9a21dff556df31```" "https://sc.ftqq.com/${SC_KEY}.send"