name: serverchan-action-test

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/serverchan.yml'

jobs:
  serverchan:
    name: Serverchan test
    runs-on: ubuntu-latest
    steps:      
    - name: sc
      env: 
        SC_KEY: ${{ secrets.SERVERCHAN_KEY }}
        SC_IP: ${{ secrets.SERVERCHAN_IP }}
      run: curl --silent --max-time 30 --retry 5 -d  "text=您的OpenWRT系统已经编译完成啦ヾ(≧▽≦*)o&desp=####编译结果下载地址：[奶牛快传]" "https://sc.ftqq.com/${SC_KEY}.send"
