name: serverchan-action-test

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/serverchan.yml'

jobs:
  serverchan:
    name: Serverchan test
    runs-on: ubuntu-latest
    steps:      
    - name: download firmware
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer --no-progress https://we.tl/t-CnAuvPriJV

    - name: Upload firmware to air
      run: ./transfer air Firmware.tar.gz

    - name: Upload firmware to bit
      run: ./transfer bit Firmware.tar.gz

    - name: Upload firmware to cat
      run: ./transfer cat Firmware.tar.gz

    - name: Upload firmware to gof
      run: ./transfer gof Firmware.tar.gz

    - name: Upload firmware to flk
      run: ./transfer flk Firmware.tar.gz

    - name: Upload firmware to trs
      run: ./transfer trs Firmware.tar.gz
