name: serverchan-action-test

on: [push]

jobs:
  serverchan:
    name: Serverchan test
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "Tiele Test1" >> title.log
          mkdir b/
          echo "body1" >> b/body.log
          echo "body233" >> b/body.log
          echo "Github Yes!" >> b/body.log
      - name: Sending message
        uses: yakumioto/serverchan-action@master
        with:
          key: ${{ secrets.SERVERCHAN_KEY }}
          text: "消息标题$(cat title.log)"
          desp: $(cat b/body.log | grep 233)"消息内容 支持MarkDown"$(cat b/body.log)