name: serverchan-action-test

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/serverchan.yml'

jobs:
  serverchan:
    name: Serverchan test
    runs-on: ubuntu-latest
    steps:      
    - name: Upload firmware to WenShuShu
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer --no-progress https://we.tl/t-CnAuvPriJV
        ./transfer air Firmware.tar.gz
        ./transfer bit Firmware.tar.gz
        ./transfer cat Firmware.tar.gz
        ./transfer gof Firmware.tar.gz
        ./transfer flk Firmware.tar.gz
        ./transfer trs Firmware.tar.gz
