name: action-test

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/test.yml'

jobs:
  serverchan:
    name: test
    runs-on: ubuntu-latest
    steps:      
    - name: sc
      env: 
        SCT_KEY: ${{ secrets.SERVERCHANT_KEY }}
      run: |
        curl --silent --max-time 30 --retry 5 -d  "title=您的OpenWRT系统已经编译完成啦ヾ(≧▽≦*)o&desp=#### 编译结果下载地址：[奶牛快传](${SC_COWTRANSFER:15})+|+[CatBox](${SC_CATBOX:15})+|+[wetransfer](${SC_WETRANSFER:15})%0D%0A%0D%0A#### [Link+To+GitHub+Actions](https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID})%0D%0A%0D%0A#### sha256:%0D%0A%0D%0A#### \`77a9f13004a03fcc6592ce8a97e31a5b150ed046ebae7eb2290f741a0350ecd9 *openwrt-x86-64-generic-ext4-combined-efi.img\`" "https://sctapi.ftqq.com/${SCT_KEY}.send"
        curl --silent --max-time 30 --retry 5 -d  "title=您的OpenWRT系统已经编译完成啦ヾ(≧▽≦*)o&desp=#### 编译结果下载地址：[奶牛快传](${SC_COWTRANSFER:15})+|+[CatBox](${SC_CATBOX:15})+|+[wetransfer](${SC_WETRANSFER:15})%0D%0A%0D%0A#### [Link+To+GitHub+Actions](https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID})%0D%0A%0D%0A#### sha256:%0D%0A%0D%0A#### `77a9f13004a03fcc6592ce8a97e31a5b150ed046ebae7eb2290f741a0350ecd9 *openwrt-x86-64-generic-ext4-combined-efi.img`" "https://sctapi.ftqq.com/${SCT_KEY}.send"
